# Generated by Django 2.0.5 on 2018-05-15 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField(default=12345678, verbose_name='学号')),
                ('s_name', models.CharField(default='某某某', max_length=20, verbose_name='学生姓名')),
                ('s_gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=6, verbose_name='学生性别')),
                ('s_birthday', models.DateField(auto_now=True, null=True, verbose_name='出生年龄')),
                ('s_class_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_platform.Class', verbose_name='所属班级')),
            ],
        ),
    ]
