# Generated by Django 2.0.5 on 2018-05-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生信息', 'verbose_name_plural': '学生信息'},
        ),
    ]
