# Generated by Django 2.0.5 on 2018-05-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180515_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField(default=12345, verbose_name='教师编号')),
                ('t_name', models.CharField(default='某某教师', max_length=20, verbose_name='教师姓名')),
                ('t_gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='教师性别')),
                ('t_phone', models.IntegerField(default=11111111111, verbose_name='教师电话号码')),
                ('t_title', models.CharField(default='教师', max_length=20, verbose_name='教师职称')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='s_gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='学生性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_name',
            field=models.CharField(default='某某学生', max_length=20, verbose_name='学生姓名'),
        ),
    ]
