# Generated by Django 2.0.5 on 2018-05-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180522_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='s_birthday',
            new_name='student_birthday',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='s_class_belong',
            new_name='student_class_belong',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='s_gender',
            new_name='student_gender',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='s_name',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='t_gender',
            new_name='teacher_gender',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='t_name',
            new_name='teacher_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='t_phone',
            new_name='teacher_phone',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='t_title',
            new_name='teacher_title',
        ),
        migrations.RemoveField(
            model_name='student',
            name='s_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='t_id',
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(default=12345678, unique=True, verbose_name='学号'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.IntegerField(default=12345, unique=True, verbose_name='教师编号'),
        ),
    ]
