# Generated by Django 2.0.5 on 2018-05-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180522_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_password',
            field=models.CharField(default=models.IntegerField(default=12345678, unique=True, verbose_name='学号'), max_length=20, verbose_name='学生账号密码'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default=models.IntegerField(default=12345, unique=True, verbose_name='教师编号'), max_length=20, verbose_name='教师账号密码'),
        ),
    ]
