# Generated by Django 2.0.5 on 2018-05-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180529_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$fgmft2SxieW3$16CoTBSGtB4QopXeepFieg5e0qhTWw54jKtwz0lHXZM=', max_length=20, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$PsC89vKr66HD$NkfsLtoG2tobC3SPXFcgSranUDa7eEHLRikgdRtOBFM=', max_length=20, verbose_name='教师账号密码'),
        ),
    ]
