# Generated by Django 2.0.5 on 2018-05-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180529_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$YPDGCNLnB7js$wsVEDo1aaf58wq8bEsatB2EZhKOH3wUw0YHDQ11iUSo=', max_length=20, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(default='某某教师', max_length=100, verbose_name='教师姓名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$cVKXFxu7JlLu$TAnJ7ELo4lebOeBoThhD8LKf2WRHKNC40lugMOjcqyk=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
