# Generated by Django 2.0.5 on 2018-05-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180529_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$Yt1YgUR36EpS$M/n1t6NnIE/2HLk7zyMwbMDglYL6dUDGU83C0X/qtOw=', max_length=20, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(default='某某教师', max_length=20, verbose_name='教师姓名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$zqkiu4QLdonR$yBTBe2zQMCDVIrT4NccBHzUlZwfCYufhivDG3CIKJzM=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
