# Generated by Django 2.0.5 on 2018-05-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180529_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$fpCVbqCr9lEv$o2crbRp/V961U0h2CbWdKsoMhRO0gtwkzielGDhc4Y0=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$6lwls3nR3Lfa$Jkn9eKSMg9LyYeQbwszfIaRcBMYxNM0UDgk0hOQHnXA=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
