# Generated by Django 2.0.5 on 2018-05-31 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0002_auto_20180531_0849'),
        ('users', '0011_auto_20180529_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_srtp_join',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='srtp_project.Project', verbose_name='所参与SRTP项目'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$c1HK2S1RWr05$WyfcXgQAo/Y7AvoPDFYzx2zibMB+AhlBsHFk9GiHuyw=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$nyfMM7YldJLu$zd95Fz4UQwwMaJ5vXd6mtJSPzLBiijzcn2H8Mka3acY=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
