# Generated by Django 2.0.5 on 2018-05-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180531_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$h13RusvB9bAI$+dY96UrAb27AOKmwl3qISEhtkD8LSHqLzZ7qX3RNwBM=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$3p65X4749669$cs0pJVPl6jU+DhCA/9wnleug7N64/t+FVoYFuxf/Jjs=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
