# Generated by Django 2.0.5 on 2018-06-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180531_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='学生邮箱'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='学生联系方式'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$P5rEFdPT1Vpn$eUBWTChNDvq479Y9mUOarpWblM1MSFrns4bsoI6icXQ=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$Lmkz40pBJYQc$m2mV/cUa7/s6fStdkE/siRyMwwfRXXkfsIOnWDmTFUo=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
