# Generated by Django 2.0.5 on 2018-06-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20180601_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_srtp_join',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$kkDOu3AZJ8Mh$tgB3pkf8pWlJRyIytPmlAYAEG45o2TtAA2MpeVGaQLA=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$hFbocaBEQSgo$tYkTvYyrT65zbqNYCCoEvkvnwwqx0svAxJ9KPDL0YDQ=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
