# Generated by Django 2.0.5 on 2018-06-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20180601_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_major',
            field=models.CharField(default='计算机科学与技术', max_length=20, verbose_name='学生所属专业'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$cjm2DsRPlPhB$og/z600FTWRVHwYPHp3Y5ImWzAlPjPXPPMyxoApB/SQ=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$azEMPwQnSzlH$7FGG9UzFGhN7Ov/o8XSacFI4zJnvT/El3Vo2XAE9Xo8=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
