# Generated by Django 2.0.5 on 2018-06-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20180603_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$E4ttOR8mI1NK$pI/F8VtCgLKeDFCa+feRjwqsH5jrW0SNuByjgCJOCc4=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$H6b9cxG6A20d$bd3/gBNbqTXo1edK4WjaBu8U7Z5Wr7S/paL8Na2Pa1k=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
