# Generated by Django 2.0.5 on 2018-06-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20180603_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$MZtMXx0JD6iz$z0LHO+rl5UjMc4G+9FZEI8sXXYhM9dkL7BUyNy0dVYM=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$ndf93fJoFzUs$k6Lpb60myHBs0T95cfNsl9kvl0DVdUKnDcK/yB+0k7c=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
