# Generated by Django 2.0.5 on 2018-06-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20180603_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$gfOKd4Mekokm$ZeXI9mAqKwev+Nxyo1U1t2Oh7ihRdkakRCISosOyhyg=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$7YHv2kfkSi7I$+zQpteNleToII7tAN+iEv/QTv+Azr4xKhHfpNqyUcD4=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
