# Generated by Django 2.0.5 on 2018-06-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20180603_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$TJuPaosGk7jb$aAe2Y5UptCiK/mv6KOG+6D7JhCcCp6mOQstAIUFGkqk=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$NzR8zIfeCSxd$T+V5DHZSu5ZO6RQQ4y1Jy8f4HuuNadi3U07z5k+evCA=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
