# Generated by Django 2.0.5 on 2018-06-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20180603_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$QPh08O05hlf1$dwrQ7UdjJ1zh8GT8DJeqUtRhiqR/3pM9yFNMWc55OBs=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$5kKjK3KLtzdF$JEyen2TSLpCyL9uaCeteMcyLEfCcRbx1pjcIC1VXtMA=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
