# Generated by Django 2.0.5 on 2018-06-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20180603_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$P7QtozC2WbMA$aWZoHiX/LT9e7Vw3QXgiQJFq+MMLVoI2yVutlk05fiI=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$80WJuMuERko6$E4sqV/QQ/watrrNvWi86zaJOdejwut9nZ6v2mQHqAy8=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
