# Generated by Django 2.0.5 on 2018-06-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20180603_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$7wPEHxLDN2uM$8DdoNhTdKXowJcrDNSKL5tLbsCIJC4ltM9sxl/Ro33c=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$A9MByd1cgID0$BQqvj0um9OMy0epqSRRqlUqwGJHrF/W8lOWn33m43IY=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
