# Generated by Django 2.0.5 on 2018-06-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20180603_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$yDlLwenesX5G$mV6SysMX1kir2+mu03GVcOSMMB+H/wplzFnxvka9+PM=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$HNT2TqGeOhLo$bowBu08vxRZ59MENBpVrkbnLALeeZTkRcX0jcCpgXzw=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
