# Generated by Django 2.0.5 on 2018-06-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20180603_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$OmLZ8nEgfJ0x$FoQbEVcO9ooUF2zpkJJyIHCiJ02Qu0HNRp7xlsQrrUQ=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$RjJwcOHRSpqK$VM+4Svb/qI6jtaHMuuVKUgi2u71yBohLnOtFnz9iVuA=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
