# Generated by Django 2.0.5 on 2018-06-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20180604_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$jIIIrla1rNod$yX9kSEjKsAxqU0zG7z0+9wDI533ktjVhI1zF9EskicE=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$j1v77up078Ph$OnQ7JExAmFbMEWfo6aki7WHXM6b148W5JyjoZp401ag=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
