# Generated by Django 2.0.5 on 2018-06-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20180604_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$DxplvWLzQYNf$MJtiViL/jbGrb2GnE1DtZRVKwwotOPA+1+tTGOnp2Cc=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$vA9NVxNvTNBS$N9jnaESA02+ml2TKta4rbEMunNa+AzYpe3S5fBEFv/w=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
