# Generated by Django 2.0.5 on 2018-06-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20180605_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$mi4hAx6lslTk$RPFNZVW1pX0e5/8r8ar2Jc19b7xwUKY1+1pZmGrka54=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$eFNIpPGBnq60$xHklMn5+g6new4BNkXTDAz1q7D5qGAapZezeHEDdCu8=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
