# Generated by Django 2.0.5 on 2018-06-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20180605_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$f02L6GSSNDbc$A2Z1qDD8gjFM9/Vjl+tIJ4S5w7qPFzusip0aexE8ej0=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$OHn8n6VIjH5H$3IdZ++NW31Lyq3HXaFFP0SG+H7UBOivFghSTZfHScE0=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
