# Generated by Django 2.0.5 on 2018-06-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20180605_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$pvLSDxikWAg2$650Ri8fPR1xTdCHlmGpLlArONKZmyEmPZ6FB2X9XVPg=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$0y6aruZEel05$S6CQRLakVOplkjXabjzlPN/rTJ75ogfyCPyOavINfuM=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
