# Generated by Django 2.0.5 on 2018-06-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20180605_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$5bmFLNHFl1DZ$OUVX7M5RPPbydj0Ax346iMHJV2THWyPz9gWWJXnBt14=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$FTwA8PWy334R$09fmGgJ5vNIDd0yozASMo2Dx5f2aR7TVb5tM+tXmOI8=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
