# Generated by Django 2.0.5 on 2018-06-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20180605_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$DeoqGuvi7zko$9x+f9EQIu4jMPZLuxWzBi3NLjByoUO2YoRGUsZgBpHk=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$or56itDWtFvv$5ndYlHeIiu+liDbNjROqDBETreB/h+PPVuqZSBHMsZc=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
