# Generated by Django 2.0.5 on 2018-06-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20180605_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$kQqq0PYmlk08$HkvjUJqMn4y/c2CatzS7c6Y8RspdCn3aNq75En8U4MI=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$fP26HU5ueKPs$xDcNh+agWh8O6kWJLo0JCb3JhofWC18ZclbWbHhB0z8=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
