# Generated by Django 2.0.5 on 2018-06-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20180605_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$rhFeHpfGAd08$tLmvm7qqgqFv6sbN0QbS50yyvE4o8AMsgRIZACquU6s=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$Nj3hgdIfnyHm$xu410rIlAzFbMbX3TpJXQVMF5Qy/zcXYRzKKbAVQpaE=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
