# Generated by Django 2.0.5 on 2018-06-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20180605_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$kvuj1n8i02gv$0yqkw66lftWQSxU8LqBlcBrMxJq+cH+WrZvYPDy++v0=', max_length=100, verbose_name='学生账号密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$TaaHXn7gvxdH$gPLi57MVjhTyCL16XQIACqlPxxBlJNLYaHvuuE7an/o=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
