# Generated by Django 2.0.5 on 2018-06-05 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='未选班级', max_length=20, unique=True, verbose_name='班级名')),
            ],
            options={
                'verbose_name': '班级信息',
                'verbose_name_plural': '班级信息',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(choices=[('Grade_one', '大一'), ('Grade_two', '大二'), ('Grade_three', '大三'), ('Grade_four', '大四')], default='Grade_one', max_length=11, unique=True, verbose_name='年级名')),
            ],
            options={
                'verbose_name': '年级信息',
                'verbose_name_plural': '年级信息',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='grade_belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_platform.Grade', verbose_name='所属年级'),
        ),
    ]
