# Generated by Django 2.0.5 on 2018-05-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': '班级信息', 'verbose_name_plural': '班级信息'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': '年级信息', 'verbose_name_plural': '年级信息'},
        ),
    ]
