# Generated by Django 2.0.5 on 2018-06-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0002_notification_notififile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notifi_id',
            field=models.IntegerField(default=123, unique=True, verbose_name='通知id'),
        ),
    ]
