# Generated by Django 2.0.5 on 2018-05-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0002_auto_20180515_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_name',
            field=models.CharField(choices=[('Grade_one', '大一'), ('Grade_two', '大二'), ('Grade_three', '大三'), ('Grade_four', '大四')], default='Grade_one', max_length=11, unique=True, verbose_name='年级名'),
        ),
    ]
