# Generated by Django 2.0.5 on 2018-05-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0003_auto_20180522_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(default='未选班级', max_length=20, unique=True, verbose_name='班级名'),
        ),
    ]
