# Generated by Django 2.0.5 on 2018-06-05 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(default=12345, verbose_name='课程编号')),
                ('course_name', models.CharField(default='xx课程', max_length=30, verbose_name='课程名称')),
                ('course_location', models.CharField(default='地点未知', max_length=20, verbose_name='课程地点')),
                ('course_point', models.IntegerField(default=2, verbose_name='课程学分')),
                ('course_length', models.IntegerField(default=32, verbose_name='课程学时')),
                ('course_startWeek', models.CharField(choices=[('week1', '第一周'), ('week2', '第二周'), ('week3', '第三周'), ('week4', '第四周'), ('week5', '第五周'), ('week6', '第六周'), ('week7', '第七周'), ('week8', '第八周'), ('week9', '第九周'), ('week10', '第十周'), ('week11', '第十一周'), ('week12', '第十二周'), ('week13', '第十三周'), ('week14', '第十四周'), ('week15', '第十五周'), ('week16', '第十六周')], default='week1', max_length=6, verbose_name='课程开始周')),
                ('course_endWeek', models.CharField(choices=[('week1', '第一周'), ('week2', '第二周'), ('week3', '第三周'), ('week4', '第四周'), ('week5', '第五周'), ('week6', '第六周'), ('week7', '第七周'), ('week8', '第八周'), ('week9', '第九周'), ('week10', '第十周'), ('week11', '第十一周'), ('week12', '第十二周'), ('week13', '第十三周'), ('week14', '第十四周'), ('week15', '第十五周'), ('week16', '第十六周')], default='week16', max_length=6, verbose_name='课程结束周')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
            },
        ),
        migrations.CreateModel(
            name='CourseTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_weekday', models.CharField(choices=[('1', '星期一'), ('2', '星期二'), ('3', '星期三'), ('4', '星期四'), ('5', '星期五')], default='1', max_length=1, verbose_name='上课时间(星期几)')),
                ('course_time', models.CharField(choices=[('1', '第一节'), ('2', '第二节'), ('3', '第三节'), ('4', '第四节'), ('5', '第五节'), ('6', '第六节')], default='1', max_length=1, verbose_name='上课时间(第几节）')),
            ],
            options={
                'verbose_name': '上课时间',
                'verbose_name_plural': '上课时间',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='course_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_arrangement.CourseTime', verbose_name='上课时间(多选)'),
        ),
    ]
