# Generated by Django 2.0.5 on 2018-06-14 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0030_auto_20180614_1059'),
        ('course_arrangement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_period', models.IntegerField(choices=[(1, '1-8'), (2, '9-16')], default=1, verbose_name='课程周期')),
                ('course_weekday', models.IntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五')], default=1, verbose_name='课程上课日')),
                ('course_time', models.IntegerField(choices=[(1, '第一节'), (2, '第二节'), (3, '第三节'), (4, '第四节'), (5, '第五节'), (6, '第六节')], default=1, verbose_name='课程时间')),
                ('course_building', models.IntegerField(choices=[(1, '逸夫楼'), (2, '教学楼'), (3, '机电楼')], default=1, verbose_name='课程建筑')),
                ('course_classroom', models.IntegerField(blank=True, default=0, null=True, verbose_name='上课教室')),
                ('selection', models.IntegerField(blank=True, editable=False, null=True, verbose_name='分配编号')),
                ('is_empty', models.BooleanField(choices=[(True, '可以分配'), (False, '不可分配')], default=True, verbose_name='分配情况')),
            ],
            options={
                'verbose_name': '课程资源分配',
                'verbose_name_plural': '课程资源分配',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_endWeek',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_length',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_location',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_startWeek',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AddField(
            model_name='course',
            name='course_capacity',
            field=models.IntegerField(default=0, verbose_name='课程容量'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_priority',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher', verbose_name='授课老师'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.IntegerField(choices=[(5, '必修'), (0, '专选')], default=0, verbose_name='课程类型'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.AutoField(default=10000, primary_key=True, serialize=False, unique=True, verbose_name='课程编号'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_point',
            field=models.IntegerField(choices=[(3, 6), (2, 32), (1, 16)], default=1, verbose_name='课程学时'),
        ),
        migrations.DeleteModel(
            name='CourseTime',
        ),
        migrations.AddField(
            model_name='course',
            name='course_selection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course_arrangement.Selection', verbose_name='资源分配'),
            preserve_default=False,
        ),
    ]
