# Generated by Django 2.0.5 on 2018-05-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_arrangement', '0002_auto_20180522_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetime',
            name='course_weekday',
            field=models.CharField(choices=[('1', '星期一'), ('2', '星期二'), ('3', '星期三'), ('4', '星期四'), ('5', '星期五')], default='1', max_length=1, verbose_name='上课时间(星期几)'),
        ),
        migrations.AlterField(
            model_name='coursetime',
            name='course_time',
            field=models.CharField(choices=[('1', '第一节'), ('2', '第二节'), ('3', '第三节'), ('4', '第四节'), ('5', '第五节'), ('6', '第六节')], default='1', max_length=1, verbose_name='上课时间(第几节）'),
        ),
    ]
