# Generated by Django 2.0.5 on 2018-06-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_arrangement', '0004_auto_20180614_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_point',
            field=models.IntegerField(choices=[(64, 64), (32, 32), (16, 16)], default=1, verbose_name='课程学时'),
        ),
    ]
