# Generated by Django 2.0.5 on 2018-06-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_arrangement', '0005_auto_20180614_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='课程编号'),
        ),
    ]
