# Generated by Django 2.0.5 on 2018-06-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0003_auto_20180608_1420'),
        ('course_arrangement', '0006_auto_20180614_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_class',
            field=models.ManyToManyField(default='上课班级', to='main_platform.Class'),
        ),
    ]
