# Generated by Django 2.0.5 on 2018-06-16 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_arrangement', '0008_auto_20180614_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_selection',
        ),
        migrations.AddField(
            model_name='course',
            name='course_selection_1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='资源分配1', to='course_arrangement.Selection', verbose_name='资源分配1'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_selection_2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='资源分配2', to='course_arrangement.Selection', verbose_name='资源分配2'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_selection_3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='资源分配3', to='course_arrangement.Selection', verbose_name='资源分配3'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_selection_4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='资源分配4', to='course_arrangement.Selection', verbose_name='资源分配4'),
        ),
        migrations.AddField(
            model_name='selection',
            name='capacity',
            field=models.BooleanField(choices=[(True, '大'), (False, '小')], default=True, verbose_name='教室大小'),
        ),
    ]
