# Generated by Django 2.0.5 on 2018-06-16 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_arrangement', '0009_auto_20180616_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_selection_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='资源分配1', to='course_arrangement.Selection', verbose_name='资源分配1'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_selection_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='资源分配2', to='course_arrangement.Selection', verbose_name='资源分配2'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_selection_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='资源分配3', to='course_arrangement.Selection', verbose_name='资源分配3'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_selection_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='资源分配4', to='course_arrangement.Selection', verbose_name='资源分配4'),
        ),
    ]
