# Generated by Django 2.0.5 on 2018-06-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_arrangement', '0011_auto_20180617_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_arranged',
            field=models.BooleanField(choices=[(True, '本课已排'), (False, '本课未排')], default=False, verbose_name='是否排课'),
        ),
    ]
