# Generated by Django 2.0.5 on 2018-06-05 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_platform', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=12345678, unique=True, verbose_name='学号')),
                ('student_name', models.CharField(default='某某学生', max_length=20, verbose_name='学生姓名')),
                ('student_password', models.CharField(default='pbkdf2_sha256$100000$a4WDeQniTE79$+S+kqdWAQHQ4RZEBOw6U5XlHqnelbWj49ztKurH2EcQ=', max_length=100, verbose_name='学生账号密码')),
                ('student_gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='学生性别')),
                ('student_birthday', models.DateField(auto_now=True, null=True, verbose_name='出生年龄')),
                ('student_phone', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='学生联系方式')),
                ('student_email', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='学生邮箱')),
                ('student_major', models.CharField(default='计算机科学与技术', max_length=20, verbose_name='学生所属专业')),
                ('student_class_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_platform.Class', verbose_name='所属班级')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
            },
        ),
    ]
