# Generated by Django 2.0.5 on 2018-06-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180605_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$KIPNSXPnkjDV$0EkalNKelbBwC+mif/b3x/S4tMCJhdQlHCC9jp8VhUw=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
