# Generated by Django 2.0.5 on 2018-06-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180605_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$SlF3cRZyDEDX$IoUlEHQt3F++iZbzUdXT00ODttImP5uaE1/nCDWQVn0=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
