# Generated by Django 2.0.5 on 2018-06-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20180606_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$TTK8FPOWxkQb$Ea52/Gj767EoUclGsfdFVVp1cUBBWCZzuvRSaKFDM+Y=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
