# Generated by Django 2.0.5 on 2018-06-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20180606_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$mqwEdVeb4ur0$kspAwfOqF6vTy4ayVyco/MtkidHGppE7iTv+H5tB0Pw=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
