# Generated by Django 2.0.5 on 2018-06-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20180607_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$nycHh2uqgbnS$f2l+hwx0KPz9ukldmrJikjD8/bkAX5tmFhPlP9q8W+w=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
