# Generated by Django 2.0.5 on 2018-06-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20180607_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$8In4c0ke5gRh$M0cIuoR6DjcYGg8Zb5Y94fogL8Fr61GIvkJrCIaybtk=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
