# Generated by Django 2.0.5 on 2018-06-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20180607_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$Edji5HqsgD25$Y7PKK4+1Ag6EJHnlMnWE2zWdOSTD7nmzdotx1BTtg+M=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
