# Generated by Django 2.0.5 on 2018-06-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20180607_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$CNx382225qJu$HqJMR7Sikg92pBOEOBTs6KArN8SL0exCOPqzPTf6SNA=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
