# Generated by Django 2.0.5 on 2018-06-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20180608_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$dpFNXTcwIjFd$p1OiZ/VICMeCwmBYT05v/ubrNl/SO6WOJbPWhDorHDo=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
