# Generated by Django 2.0.5 on 2018-06-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20180608_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$Q8oP6FAJhxlH$Zv/MehyLvfjn4C2Jgw+/syr9yl6VGJJnyIRsu46E8V4=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
