# Generated by Django 2.0.5 on 2018-06-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20180608_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$oj2fSOAuYnN5$3V+45yTBXTpq1MvUIgy6iD4IsAfM4bnSwMT34fvbeU0=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
