# Generated by Django 2.0.5 on 2018-06-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20180609_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$ExoAxZJ6UNMT$K68hO6KwRE7Vg31/WVtlfHqNM1VkTr4ONdF13VBcPWQ=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
