# Generated by Django 2.0.5 on 2018-06-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_auto_20180609_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$u7HSW3bv6vU0$mT/8PlULckECeE2PcIq1fnkcC/A0UjDLFdeAhatHW9w=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
