# Generated by Django 2.0.5 on 2018-06-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_auto_20180609_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$4OulNYdxoeKB$cQZZMv16vEVWlxuEboh80lVk0o4sfD8HN5yHzyPw2v8=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
