# Generated by Django 2.0.5 on 2018-06-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_auto_20180609_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$MwyicB6y8cYZ$eCWaRkz1QrtUpK6nwerCoA3LOnT48N/+C6vaHXI2SlM=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
