# Generated by Django 2.0.5 on 2018-06-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_auto_20180609_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$4MIwW0ayGFpf$c/vwFDs4OlmjL/gNoGZHI2QWFG5R/ske/v4xmrz8pw8=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
