# Generated by Django 2.0.5 on 2018-06-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_auto_20180614_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$ESuoyQEnGDih$qc03uPA62XCxrmqw5cc4MFilk4dnSUgYZIj3TL4kXGg=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
