# Generated by Django 2.0.5 on 2018-06-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_auto_20180614_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$4GluQS82arWo$afwEiibOfIAxjd5I20j5yrI1ole0zYyehOQOHIWOFZc=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
