# Generated by Django 2.0.5 on 2018-06-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_auto_20180614_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$ZCJCNgxFCgpl$1d3HDooQabV+N+dlBb5LTfvBAQQtnJ0cCAofIcpXlao=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
