# Generated by Django 2.0.5 on 2018-06-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_auto_20180614_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$7RSaKHbQ2IaH$iyuVN1/arBC7FuLKasa6Ih9G5H85W4Zde9aF+X+sp4I=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
