# Generated by Django 2.0.5 on 2018-06-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_auto_20180614_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$bzlIdy6lRe68$no++EptEa7Ciq/omPUbmpUVz3IIEWzVBcLzUkfcZ0yM=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
