# Generated by Django 2.0.5 on 2018-06-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0035_auto_20180614_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$Xa2YoNmPZuGv$xpb/5yKtD9DocaDm5ps2HpXERzHdpEX1pJXeNrMEyPA=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
