# Generated by Django 2.0.5 on 2018-06-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_merge_20180614_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$GOzDH54wH96x$9DIJ+WPPw8H2X128gntyxls61+aViGZSN8Wd52NW44k=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
