# Generated by Django 2.0.5 on 2018-06-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0038_auto_20180614_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$8Bn6NK6rFgYL$Xkcw8TTL+5TlwEjUS5MPBjNKFMsJaO5YCDvjfoNAVZk=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
