# Generated by Django 2.0.5 on 2018-06-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_auto_20180616_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$FF9RZhSOjmox$5XpN+Lif50K0L4Bg5mt5lxH+qOATxH5TVvbRP8+GFd4=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
