# Generated by Django 2.0.5 on 2018-06-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0040_auto_20180616_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$KC7U3KXtvMrX$JqzO6PQCatVBdQEZ3htwa1DE3AohFI1QLdxaxsMJmrU=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
