# Generated by Django 2.0.5 on 2018-06-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0042_auto_20180617_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$6ezEP3kFZSHa$/2ZWzq1JvdDl3zApCN5Bc3nX68bK26OPTVMx3zI0UOw=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
