# Generated by Django 2.0.5 on 2018-06-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0042_auto_20180617_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$UHuORFc5bfNI$wt0vHGlA18XwhrzsvGxfzRg0Dx2gltKz/K9JmbptawE=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
