# Generated by Django 2.0.5 on 2018-06-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0043_auto_20180617_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='pbkdf2_sha256$100000$bouGWLCqfYAu$CgL5TTtFvcHeeB3zR50WW7+c/tNsiqxoHslHYO14iBQ=', max_length=100, verbose_name='学生账号密码'),
        ),
    ]
