# Generated by Django 2.0.5 on 2018-06-07 21:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0017_auto_20180607_2137'),
        ('student', '0017_auto_20180607_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dissertation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default='暂未命名', max_length=100, null=True, verbose_name='毕业论文文档名称')),
                ('file_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='毕业论文文件路径')),
                ('student_belong', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='创作学生')),
                ('teacher_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher', verbose_name='指导老师')),
            ],
            options={
                'verbose_name': '毕业论文',
                'verbose_name_plural': '毕业论文',
            },
        ),
        migrations.CreateModel(
            name='MidtermReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default='暂未命名', max_length=100, null=True, verbose_name='中期报告文档名称')),
                ('file_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='中期报告文件路径')),
                ('student_belong', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='创作学生')),
                ('teacher_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher', verbose_name='指导老师')),
            ],
            options={
                'verbose_name': '开题报告',
                'verbose_name_plural': '开题报告',
            },
        ),
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default='暂未命名', max_length=100, null=True, verbose_name='文档模板名称')),
                ('file_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件路径')),
                ('file_date', models.DateField(default=django.utils.timezone.now, verbose_name='模板文件发布日期')),
            ],
            options={
                'verbose_name': '文档模板',
                'verbose_name_plural': '文档模板',
            },
        ),
        migrations.CreateModel(
            name='OpeningReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default='暂未命名', max_length=100, null=True, verbose_name='开题报告文档名称')),
                ('file_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件路径')),
                ('student_belong', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='创作学生')),
                ('teacher_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher', verbose_name='指导老师')),
            ],
            options={
                'verbose_name': '开题报告',
                'verbose_name_plural': '开题报告',
            },
        ),
    ]
