# Generated by Django 2.0.5 on 2018-06-07 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissertation',
            name='file_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='上传日期'),
        ),
        migrations.AddField(
            model_name='midtermreport',
            name='file_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='上传日期'),
        ),
        migrations.AddField(
            model_name='openingreport',
            name='file_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='file_name',
            field=models.CharField(blank=True, default='暂未命名', max_length=100, null=True, verbose_name='文档名称'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='file_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='midtermreport',
            name='file_name',
            field=models.CharField(blank=True, default='暂未命名', max_length=100, null=True, verbose_name='文档名称'),
        ),
        migrations.AlterField(
            model_name='midtermreport',
            name='file_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='file_name',
            field=models.CharField(blank=True, default='暂未命名', max_length=100, null=True, verbose_name='文件名称'),
        ),
        migrations.AlterField(
            model_name='openingreport',
            name='file_name',
            field=models.CharField(blank=True, default='暂未命名', max_length=100, null=True, verbose_name='文件名称'),
        ),
    ]
