# Generated by Django 2.0.5 on 2018-06-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField(default=12345, unique=True, verbose_name='教师编号')),
                ('teacher_password', models.CharField(default='pbkdf2_sha256$100000$DjS0xVgUC9OQ$GJn60+/8zomAFo7GDiJ9vaehfHu/FgXs98MnosxOTTU=', max_length=100, verbose_name='教师账号密码')),
                ('teacher_name', models.CharField(default='某某教师', max_length=20, verbose_name='教师姓名')),
                ('teacher_gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='教师性别')),
                ('teacher_phone', models.IntegerField(default=11111111111, verbose_name='教师电话号码')),
                ('teacher_email', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='教师邮箱')),
                ('teacher_title', models.CharField(default='教师', max_length=20, verbose_name='教师职称')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
            },
        ),
    ]
