# Generated by Django 2.0.5 on 2018-06-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$6n9zchpMjlhU$TLgcBfVnSgMFU/mo+8XvwDqglR4nv2l5luzA5WMG7Xo=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
