# Generated by Django 2.0.5 on 2018-06-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20180605_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$dW0aDXsTncnr$xFXWFGZF/f4CK+Ku+7TdFS26s8yLuKkjzVtVL/DCBe4=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
