# Generated by Django 2.0.5 on 2018-06-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20180605_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$hrAySxyQxb3u$Pl6L7D0iqq9KfksTJkb6lz/+cyIFEnZb59VfHSjM4N0=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
