# Generated by Django 2.0.5 on 2018-06-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20180606_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$qZBikR4yZesp$Hr6vlF6yIjBvBW9dumZ54V4zOXmck0HRdGfF2upOqts=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
