# Generated by Django 2.0.5 on 2018-06-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_auto_20180607_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$XQ18qgFKt6Wk$WoW+LufYMsCVwwXSvYXx8sh2ggWYR4wdGQmb0MibiN0=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
