# Generated by Django 2.0.5 on 2018-06-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_auto_20180607_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$uE13EHqTqsEA$PBcog+9/RINKeTtkOJuwxEjoKMK6QXo0bZ7q9wwJiRw=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
