# Generated by Django 2.0.5 on 2018-06-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_auto_20180607_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$W7CyyNUF1Y0b$V4A2OkShf0WmVj7VAG5cYC72KUxOV0lwaP+rVriZ2HA=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
