# Generated by Django 2.0.5 on 2018-06-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_auto_20180607_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$705Gs4noiMvP$MZMCXDX6Dz31e7JYu9j0flpYhjjG4dcjjE1WaxeGvVI=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
