# Generated by Django 2.0.5 on 2018-06-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_auto_20180607_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$CTCTLt7se6PL$IlfA/GMPbMRVVBZsCwQF+ghrd8kcPEc6L/Ol38ox20U=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
