# Generated by Django 2.0.5 on 2018-06-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_auto_20180607_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$sZJMIO883jEG$dMUQACV1s7C7r9BLQZ0RZMM5iyntrrVEs3sKfHR5p0k=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
