# Generated by Django 2.0.5 on 2018-06-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_auto_20180607_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$0SBkE0u98AEf$F+t65UZmy1zEUwwFQQ1WkAho/1MqSgyOB1x0jdAqi6Y=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
