# Generated by Django 2.0.5 on 2018-06-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0017_auto_20180607_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$GPPuqkaU9u4i$OFgVs94nwioIsFXLglC8tHcAZUUNyQW6S2j3cR9TRg0=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
