# Generated by Django 2.0.5 on 2018-06-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0019_auto_20180608_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$f4mWMcPO9Uf8$bxtiL3fBuHnbVdJUswhwm7ZwNNuuRbuHS/iSPb9eLwA=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
