# Generated by Django 2.0.5 on 2018-06-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0020_auto_20180608_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$eU2puBiMbwr9$tQVfXsNLXQN+9f20deq3VtygmJ+xEzer7z1CvO91YGA=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
