# Generated by Django 2.0.5 on 2018-06-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0021_auto_20180608_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$CgbeXdCdN5q8$N3x5q1VrRubrHRqJY69ON6Z5XSpBqtnwPIGmrCTaPIA=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
