# Generated by Django 2.0.5 on 2018-06-09 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0022_auto_20180609_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_duty',
            field=models.CharField(default='暂未填写', max_length=20, verbose_name='教师职务'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_major',
            field=models.CharField(default='暂未填写', max_length=20, verbose_name='教师专业'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$qLqzOh5Td7vN$j9js+IExYtWztN6yIgOmBgexUJqHcRkErd3IvRAcRM8=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
