# Generated by Django 2.0.5 on 2018-06-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0023_auto_20180609_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$HYxmEHMNa3pd$T4AUPzO0OcJDJhNRt2+vAgRvoRGDxLuJeSoVRpca4ww=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
