# Generated by Django 2.0.5 on 2018-06-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0024_auto_20180609_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$nYtHA5y3ds1r$5vhQy0hozbjouy8wWLisGk/1CJQo1tchc1eAB0Qv85o=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
