# Generated by Django 2.0.5 on 2018-06-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0026_auto_20180609_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$IgqdQXzI3LTG$1Ry9BXcWUxeXpkXO/DhmM7IesoIXRGClEs23zur3IJA=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
