# Generated by Django 2.0.5 on 2018-06-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0028_auto_20180609_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$0OpbzEy0zLYB$u1Z8P0C9MAHwEGLKKJg/IevCG0KOnodvT7oXG53bFGM=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
