# Generated by Django 2.0.5 on 2018-06-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0029_auto_20180609_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$1lj1Y8cXmE2j$hTi7zHH0QE1sPemKbkxUDetZ/9zBIEDRKrXTTA81gwI=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
