# Generated by Django 2.0.5 on 2018-06-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0034_auto_20180614_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$pnZvW1AnDlgR$KSYRdCB+Xt4l9ZvtywECtItAHrrrXZKQ8DK0PDG0/BI=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
