# Generated by Django 2.0.5 on 2018-06-14 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0034_auto_20180614_1122'),
        ('teacher', '0036_auto_20180614_1136'),
    ]

    operations = [
    ]
