# Generated by Django 2.0.5 on 2018-06-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0037_merge_20180614_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$QfxXfcSZvyrw$GmT3l4fQ7K4MKw1/MMrdb0ansY4ax9uz+HF/5c27a/c=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
