# Generated by Django 2.0.5 on 2018-06-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0040_auto_20180616_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$C3pOwI42tiyG$A8zizyx0ni73O9uPY5sFw2TbnAsBXf2EO91SCXEp+3E=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
