# Generated by Django 2.0.5 on 2018-06-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0041_auto_20180616_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$XAmTlfAc1qAH$Y/f5iDrlfCxDSXqayk08pIBQXIs+zlEu4hWP/9XXgB8=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
