# Generated by Django 2.0.5 on 2018-06-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0042_auto_20180617_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$SKGqW7gVhymi$UFBuQf/5kA89kmRthyizXJF75GZrNTOauVz8S0A4v1c=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
