# Generated by Django 2.0.5 on 2018-06-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0042_auto_20180617_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_password',
            field=models.CharField(default='pbkdf2_sha256$100000$rl1ZRVrczXNl$xu48KbcpTGqhoQ7AGb1Q2GD4NIf8Vxeq6vl2yp4BIXE=', max_length=100, verbose_name='教师账号密码'),
        ),
    ]
