# Generated by Django 2.0.5 on 2018-06-09 10:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0024_auto_20180609_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educonclusion_file_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名称')),
                ('educonclusion_file_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件路径')),
                ('educonclusion_deadline_date', models.DateField(default=django.utils.timezone.now, verbose_name='提交截止日期')),
                ('educonclusion_check_status', models.CharField(choices=[('0', '未提交'), ('1', '审批中'), ('2', '已通过')], default='0', max_length=1, verbose_name='审核状态')),
            ],
            options={
                'verbose_name': '教改/教研/教材项目结题',
                'verbose_name_plural': '教改/教研/教材项目结题',
            },
        ),
        migrations.CreateModel(
            name='EduMidTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edumidterm_file_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名称')),
                ('edumidterm_file_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件路径')),
                ('edumidterm_deadline_date', models.DateField(default=django.utils.timezone.now, verbose_name='提交截止日期')),
                ('edumidterm_check_status', models.CharField(choices=[('0', '未提交'), ('1', '审批中'), ('2', '已通过')], default='0', max_length=1, verbose_name='审核状态')),
            ],
            options={
                'verbose_name': '教改/教研/教材项目中期检查',
                'verbose_name_plural': '教改/教研/教材项目中期检查',
            },
        ),
        migrations.CreateModel(
            name='EduProject',
            fields=[
                ('eduproject_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='项目编号')),
                ('eduproject_name', models.CharField(default='xx项目', max_length=20, verbose_name='项目名称')),
                ('eduproject_belong_unit', models.CharField(default='xx单位', max_length=20, verbose_name='申请单位')),
                ('eduproject_fund_appli', models.IntegerField(default=3000, verbose_name='项目申请经费')),
                ('eduproject_type', models.CharField(choices=[('zd', '重点'), ('zdzx', '重点专项'), ('ms', '面上')], default='zd', max_length=2, verbose_name='项目类别')),
                ('eduproject_date_begin', models.DateField(default=django.utils.timezone.now, verbose_name='起始日期')),
                ('eduproject_date_end', models.DateField(default=django.utils.timezone.now, verbose_name='结束日期')),
                ('eduproject_appli_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目申请书名称')),
                ('eduproject_appli_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目申请书路径')),
                ('eduproject_member', models.CharField(blank=True, default='暂未填写', max_length=50, null=True, verbose_name='项目成员')),
                ('eduproject_person_in_charge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher', verbose_name='项目负责人')),
            ],
            options={
                'verbose_name': '教改/教研/教材项目信息',
                'verbose_name_plural': '教改/教研/教材项目信息',
            },
        ),
        migrations.AddField(
            model_name='edumidterm',
            name='eduproject_belong',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edu_reform.EduProject', verbose_name='所属教改/教研/教材项目'),
        ),
        migrations.AddField(
            model_name='conclusion',
            name='eduproject_belong',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edu_reform.EduProject', verbose_name='所属教改/教研/教材项目'),
        ),
    ]
