# Generated by Django 2.0.5 on 2018-06-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_reform', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conclusion',
            new_name='EduConclusion',
        ),
    ]
