# Generated by Django 2.0.5 on 2018-06-09 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_reform', '0004_edufund_eduresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduproject',
            name='eduproject_person_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher', verbose_name='项目负责人'),
        ),
    ]
