# Generated by Django 2.0.5 on 2018-06-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_reform', '0005_auto_20180609_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educonclusion',
            options={'verbose_name': '教改-教研-教材项目结题', 'verbose_name_plural': '教改-教研-教材项目结题'},
        ),
        migrations.AlterModelOptions(
            name='edumidterm',
            options={'verbose_name': '教改-教研-教材项目中期检查', 'verbose_name_plural': '教改-教研-教材项目中期检查'},
        ),
        migrations.AlterModelOptions(
            name='eduproject',
            options={'verbose_name': '教改-教研-教材项目信息', 'verbose_name_plural': '教改-教研-教材项目信息'},
        ),
    ]
