# Generated by Django 2.0.5 on 2018-05-31 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SRTPproject',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='项目编号')),
                ('project_name', models.CharField(default='xx项目', max_length=20, verbose_name='项目名称')),
                ('project_type', models.CharField(choices=[('cx', '创新'), ('cy', '创业')], default='cx', max_length=2, verbose_name='项目类型')),
                ('project_rank', models.CharField(choices=[('1', '一级'), ('2', '二级'), ('3', '三级'), ('4', '四级'), ('5', '五级')], default='1', max_length=1, verbose_name='项目等级')),
                ('project_intro', models.CharField(blank=True, max_length=1000, verbose_name='项目简介')),
                ('project_depart', models.CharField(choices=[('tm', '土木与资源工程学院'), ('yj', '冶金与生态工程学院'), ('cl', '材料科学与工程学院'), ('jx', '机械工程学院'), ('nh', '能源与环境工程学院'), ('zdh', '自动化学院'), ('jt', '计算机与通信工程学院'), ('sl', '数理学院'), ('hs', '化学与生物工程学院'), ('jg', '东凌经济管理学院'), ('wf', '文法学院'), ('mks', '马克思主义学院'), ('wgy', '外国语学院'), ('gg', '高等工程师学院')], default='jt', max_length=3, verbose_name='项目所属学院')),
                ('project_plan', models.CharField(blank=True, default='2018年创新计划', max_length=10, verbose_name='项目所属创新计划')),
                ('project_form', models.CharField(default='实体', max_length=40, verbose_name='项目成果形式')),
                ('project_appli_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目申请书')),
                ('project_fund_appli', models.IntegerField(default=3000, verbose_name='项目申请经费')),
                ('project_fund_approv', models.IntegerField(default=3000, verbose_name='项目批准经费')),
                ('project_date_begin', models.DateTimeField(default=django.utils.timezone.now, verbose_name='项目立项日期')),
                ('project_date_end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='项目结束日期')),
            ],
            options={
                'verbose_name': 'SRTP项目信息',
                'verbose_name_plural': 'SRTP项目信息',
            },
        ),
    ]
