# Generated by Django 2.0.5 on 2018-06-05 20:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_auto_20180605_2051'),
        ('teacher', '0002_auto_20180605_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addfund_date', models.DateField(default=django.utils.timezone.now, verbose_name='追加经费申请时间')),
                ('addfund_num', models.IntegerField(blank=True, null=True, verbose_name='追加经费数目')),
                ('addfund_reason', models.TextField(blank=True, null=True, verbose_name='追加经费理由')),
                ('addfund_check_status', models.CharField(choices=[('0', '未通过'), ('1', '通过')], default='0', max_length=1, verbose_name='追加经费审核状态')),
                ('addfund_add_status', models.CharField(choices=[('0', '未添加'), ('1', '已添加')], default='0', editable=False, max_length=1, verbose_name='追加经费添加状态')),
            ],
            options={
                'verbose_name': 'SRTP项目追加经费',
                'verbose_name_plural': 'SRTP项目追加经费',
            },
        ),
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion_file_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名称')),
                ('conclusion_file_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件路径')),
                ('conclusion_deadline_date', models.DateField(default=django.utils.timezone.now, verbose_name='提交截止日期')),
                ('conclusion_check_status', models.CharField(choices=[('0', '未提交'), ('1', '审批中'), ('2', '已通过')], default='0', max_length=1, verbose_name='审核状态')),
                ('conclusion_check_point', models.CharField(choices=[('0', ''), ('1', '教师审核'), ('2', '管理员审核')], default='0', max_length=1, verbose_name='审核节点')),
            ],
            options={
                'verbose_name': 'SRTP项目结题检查',
                'verbose_name_plural': 'SRTP项目结题检查',
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='具体支出项目摘要')),
                ('fund_type', models.CharField(choices=[('1', '差旅费'), ('2', '实验费'), ('3', '资料费'), ('4', '实验耗材费'), ('5', '计算机小型存储设备费'), ('6', '邮寄费'), ('7', '论文版面费'), ('8', '成果鉴定费'), ('9', '专利申请费'), ('10', '文件检索费'), ('11', '办公费'), ('12', '其他费用')], default='12', max_length=9, verbose_name='经费类别')),
                ('fund_num', models.IntegerField(blank=True, null=True, verbose_name='经费支出金额')),
                ('fund_date', models.DateField(default=django.utils.timezone.now, verbose_name='经费支出日期')),
            ],
            options={
                'verbose_name': 'SRTP项目经费管理',
                'verbose_name_plural': 'SRTP项目经费管理',
            },
        ),
        migrations.CreateModel(
            name='MidTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midterm_file_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名称')),
                ('midterm_file_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件路径')),
                ('midterm_deadline_date', models.DateField(default=django.utils.timezone.now, verbose_name='提交截止日期')),
                ('midterm_check_status', models.CharField(choices=[('0', '未提交'), ('1', '审批中'), ('2', '已通过')], default='0', max_length=1, verbose_name='审核状态')),
                ('midterm_check_point', models.CharField(choices=[('0', ''), ('1', '教师审核'), ('2', '管理员审核')], default='0', max_length=1, verbose_name='审核节点')),
            ],
            options={
                'verbose_name': 'SRTP项目中期检查',
                'verbose_name_plural': 'SRTP项目中期检查',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='项目编号')),
                ('project_name', models.CharField(default='xx项目', max_length=20, verbose_name='项目名称')),
                ('project_type', models.CharField(choices=[('cx', '创新'), ('cy', '创业')], default='cx', max_length=2, verbose_name='项目类型')),
                ('project_rank', models.CharField(choices=[('1', '一级'), ('2', '二级'), ('3', '三级'), ('4', '四级'), ('5', '五级')], default='1', max_length=1, verbose_name='项目等级')),
                ('project_intro', models.CharField(blank=True, max_length=1000, verbose_name='项目简介')),
                ('project_depart', models.CharField(choices=[('tm', '土木与资源工程学院'), ('yj', '冶金与生态工程学院'), ('cl', '材料科学与工程学院'), ('jx', '机械工程学院'), ('nh', '能源与环境工程学院'), ('zdh', '自动化学院'), ('jt', '计算机与通信工程学院'), ('sl', '数理学院'), ('hs', '化学与生物工程学院'), ('jg', '东凌经济管理学院'), ('wf', '文法学院'), ('mks', '马克思主义学院'), ('wgy', '外国语学院'), ('gg', '高等工程师学院')], default='jt', max_length=3, verbose_name='项目所属学院')),
                ('project_plan', models.CharField(blank=True, default='2018年创新计划', max_length=10, verbose_name='项目所属创新计划')),
                ('project_form', models.CharField(default='实体', max_length=40, verbose_name='项目成果形式')),
                ('project_appli_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目申请书名称')),
                ('project_appli_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目申请书路径')),
                ('project_fund_appli', models.IntegerField(default=3000, verbose_name='项目申请经费')),
                ('project_fund_approv', models.IntegerField(default=3000, verbose_name='项目批准经费')),
                ('project_date_begin', models.DateField(default=django.utils.timezone.now, verbose_name='项目立项日期')),
                ('project_date_end', models.DateField(default=django.utils.timezone.now, verbose_name='项目结束日期')),
                ('project_period', models.CharField(default='1年', max_length=10, verbose_name='项目周期')),
                ('project_member', models.CharField(blank=True, default='暂未填写', max_length=50, null=True, verbose_name='项目成员')),
                ('project_status', models.BooleanField(choices=[(True, '通过'), (False, '未通过')], default=False, verbose_name='项目审核状态')),
                ('project_appli_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='项目申请人')),
                ('project_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher', verbose_name='项目指导老师')),
            ],
            options={
                'verbose_name': 'SRTP项目信息',
                'verbose_name_plural': 'SRTP项目信息',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_name', models.CharField(default='未命名成果', max_length=50, verbose_name='项目成果名称')),
                ('result_type', models.CharField(choices=[('1', '著作/著作权'), ('2', '论文'), ('3', '专利'), ('4', '实物'), ('5', '软件/图纸/设计'), ('6', '获奖证书'), ('7', '其他')], default='7', max_length=8, verbose_name='项目成果类型')),
                ('result_date', models.DateField(default=django.utils.timezone.now, verbose_name='项目成果日期')),
                ('result_master', models.CharField(default='未填写', max_length=20, verbose_name='项目成果所有人')),
                ('result_file_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目附件名称')),
                ('result_file_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目附件路径')),
                ('project_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srtp_project.Project', verbose_name='所属srtp项目')),
            ],
            options={
                'verbose_name': 'SRTP项目成果管理',
                'verbose_name_plural': 'SRTP项目成果管理',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('schedule_num', models.IntegerField(default=1, verbose_name='项目进度')),
                ('schedule_detail', models.TextField(default='缺少说明，请补充', verbose_name='项目进展说明')),
                ('project_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srtp_project.Project', verbose_name='所属srtp项目')),
            ],
            options={
                'verbose_name': 'SRTP项目进度',
                'verbose_name_plural': 'SRTP项目进度',
            },
        ),
        migrations.AddField(
            model_name='midterm',
            name='project_belong',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='srtp_project.Project', verbose_name='所属srtp项目'),
        ),
        migrations.AddField(
            model_name='fund',
            name='project_belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srtp_project.Project', verbose_name='所属srtp项目'),
        ),
        migrations.AddField(
            model_name='conclusion',
            name='project_belong',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='srtp_project.Project', verbose_name='所属srtp项目'),
        ),
        migrations.AddField(
            model_name='addfund',
            name='project_belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srtp_project.Project', verbose_name='所属srtp项目'),
        ),
    ]
