# Generated by Django 2.0.5 on 2018-05-31 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180529_1510'),
        ('srtp_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SRTPproject',
            new_name='Project',
        ),
    ]
