# Generated by Django 2.0.5 on 2018-06-06 08:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0002_auto_20180605_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifi_id', models.IntegerField(default=1528245836, verbose_name='通知id')),
                ('notifi_date', models.DateField(default=django.utils.timezone.now, verbose_name='通知发布时间')),
                ('notifi_title', models.CharField(default='未命名消息通知', max_length=50, verbose_name='通知标题')),
                ('notifi_content', models.TextField(blank=True, null=True, verbose_name='通知内容')),
            ],
            options={
                'verbose_name': 'SRTP项目消息通知',
                'verbose_name_plural': 'SRTP项目消息通知',
            },
        ),
        migrations.CreateModel(
            name='NotifiFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifi_file_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='通知附件名称')),
                ('notifi_file_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='通知附件路径')),
                ('notifi_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srtp_project.Notification', verbose_name='所属通知')),
            ],
            options={
                'verbose_name': 'SRTP项目通知附件',
                'verbose_name_plural': 'SRTP项目通知附件',
            },
        ),
    ]
