# Generated by Django 2.0.5 on 2018-05-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0002_auto_20180531_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.BooleanField(choices=[(True, '通过'), (False, '未通过')], default=False, verbose_name='项目审核状态'),
        ),
    ]
