# Generated by Django 2.0.5 on 2018-05-31 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0003_project_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_date_begin',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='项目立项日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_date_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='项目结束日期'),
        ),
    ]
