# Generated by Django 2.0.5 on 2018-06-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0004_auto_20180606_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notifi_id',
            field=models.IntegerField(default=1528253320, unique=True, verbose_name='通知id'),
        ),
    ]
