# Generated by Django 2.0.5 on 2018-06-01 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180601_2057'),
        ('srtp_project', '0004_auto_20180531_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_student',
            field=models.OneToOneField(default=12345678, on_delete=django.db.models.deletion.CASCADE, to='users.Student', verbose_name='项目参与学生'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_teacher',
            field=models.ForeignKey(default=12345, on_delete=django.db.models.deletion.CASCADE, to='users.Teacher', verbose_name='项目指导老师'),
            preserve_default=False,
        ),
    ]
