# Generated by Django 2.0.5 on 2018-06-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0005_auto_20180606_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_suggest_people_num',
            field=models.CharField(blank=True, default='暂未填写', max_length=50, null=True, verbose_name='人数建议'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notifi_id',
            field=models.IntegerField(default=1528349654, unique=True, verbose_name='通知id'),
        ),
    ]
