# Generated by Django 2.0.5 on 2018-06-03 09:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0006_auto_20180603_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('schedule_num', models.IntegerField(default=1, verbose_name='项目进度')),
                ('schedule_detail', models.TextField(default='缺少说明，请补充', verbose_name='项目进展说明')),
                ('project_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srtp_project.Project', verbose_name='所属srtp项目')),
            ],
            options={
                'verbose_name': 'SRTP项目进度',
                'verbose_name_plural': 'SRTP项目进度',
            },
        ),
    ]
