# Generated by Django 2.0.5 on 2018-06-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0007_auto_20180607_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notifi_file_url',
            field=models.FileField(blank=True, default='', null=True, upload_to='SrtpNotification/', verbose_name='通知附件路径'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notifi_id',
            field=models.IntegerField(default=1528366978, unique=True, verbose_name='通知id'),
        ),
    ]
