# Generated by Django 2.0.5 on 2018-06-03 15:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0008_auto_20180603_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='具体支出项目摘要')),
                ('fund_type', models.CharField(choices=[('cl', '差旅费'), ('sy', '实验费'), ('zl', '资料费'), ('syhc', '实验耗材费'), ('jsjxxccsb', '计算机小型存储设备费'), ('yj', '邮寄费'), ('lwbm', '论文版面费'), ('cgjd', '成果鉴定费'), ('zlsq', '专利申请费'), ('bg', '办公费'), ('qt', '其他费用')], default='qt', max_length=9, verbose_name='经费类别')),
                ('fund_num', models.IntegerField(blank=True, null=True, verbose_name='经费支出金额')),
                ('fund_date', models.DateField(default=django.utils.timezone.now, verbose_name='经费支出日期')),
                ('project_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srtp_project.Project', verbose_name='所属srtp项目')),
            ],
            options={
                'verbose_name': 'SRTP项目经费管理',
                'verbose_name_plural': 'SRTP项目经费管理',
            },
        ),
    ]
