# Generated by Django 2.0.5 on 2018-06-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0008_auto_20180607_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notifi_file_url',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notifi_id',
            field=models.IntegerField(default=1528367228, unique=True, verbose_name='通知id'),
        ),
        migrations.AlterField(
            model_name='notififile',
            name='notifi_file_url',
            field=models.FileField(blank=True, default='', null=True, upload_to='SrtpNotification/', verbose_name='通知附件路径'),
        ),
    ]
