# Generated by Django 2.0.5 on 2018-06-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0009_auto_20180607_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notifi_id',
            field=models.IntegerField(default=1528369570, unique=True, verbose_name='通知id'),
        ),
        migrations.AlterField(
            model_name='notififile',
            name='notifi_file_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='通知附件名称'),
        ),
        migrations.AlterField(
            model_name='notififile',
            name='notifi_file_url',
            field=models.FileField(blank=True, default='', null=True, unique=True, upload_to='SrtpNotification/', verbose_name='通知附件路径'),
        ),
    ]
