# Generated by Django 2.0.5 on 2018-06-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0010_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='fund_type',
            field=models.CharField(choices=[('1', '差旅费'), ('2', '实验费'), ('3', '资料费'), ('4', '实验耗材费'), ('5', '计算机小型存储设备费'), ('6', '邮寄费'), ('7', '论文版面费'), ('8', '成果鉴定费'), ('9', '专利申请费'), ('10', '文件检索费'), ('11', '办公费'), ('12', '其他费用')], default='12', max_length=9, verbose_name='经费类别'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_type',
            field=models.CharField(choices=[('1', '著作/著作权'), ('2', '论文'), ('3', '专利'), ('4', '实物'), ('5', '软件/图纸/设计'), ('6', '获奖证书'), ('7', '其他')], default='7', max_length=8, verbose_name='项目成果类型'),
        ),
    ]
