# Generated by Django 2.0.5 on 2018-06-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0010_auto_20180607_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notifi_id',
            field=models.IntegerField(default=1528370207, unique=True, verbose_name='通知id'),
        ),
    ]
