# Generated by Django 2.0.5 on 2018-06-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0011_auto_20180607_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='notififile',
            name='notifi_file_status',
            field=models.BooleanField(default=False, editable=False, verbose_name='附件路径与名字修改状态'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notifi_id',
            field=models.IntegerField(default=1528370692, unique=True, verbose_name='通知id'),
        ),
    ]
