# Generated by Django 2.0.5 on 2018-06-04 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0011_auto_20180603_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addfund_num', models.IntegerField(blank=True, null=True, verbose_name='追加经费数目')),
                ('addfund_reason', models.TextField(blank=True, null=True, verbose_name='追加经费理由')),
                ('project_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srtp_project.Project', verbose_name='所属srtp项目')),
            ],
            options={
                'verbose_name': 'SRTP项目追加经费',
                'verbose_name_plural': 'SRTP项目追加经费',
            },
        ),
    ]
