# Generated by Django 2.0.5 on 2018-06-05 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0012_addfund'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfund',
            name='addfund_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='追加经费申请时间'),
        ),
        migrations.AddField(
            model_name='addfund',
            name='addfund_state',
            field=models.CharField(choices=[('0', '未通过'), ('1', '通过')], default='0', max_length=1, verbose_name='追加经费审核状态'),
        ),
    ]
