# Generated by Django 2.0.5 on 2018-06-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0013_auto_20180607_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notifi_id',
            field=models.IntegerField(default=1528370894, unique=True, verbose_name='通知id'),
        ),
        migrations.AlterField(
            model_name='notififile',
            name='notifi_file_name',
            field=models.CharField(blank=True, default='暂未命名', max_length=100, null=True, verbose_name='通知附件名称'),
        ),
    ]
