# Generated by Django 2.0.5 on 2018-06-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0013_auto_20180605_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addfund',
            old_name='addfund_state',
            new_name='addfund_check_status',
        ),
        migrations.AddField(
            model_name='addfund',
            name='addfund_add_status',
            field=models.CharField(choices=[('0', '未添加'), ('1', '已添加')], default='0', max_length=1, verbose_name='追加经费添加状态'),
        ),
    ]
