# Generated by Django 2.0.5 on 2018-06-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0014_auto_20180605_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfund',
            name='addfund_add_status',
            field=models.CharField(choices=[('0', '未添加'), ('1', '已添加')], default='0', editable=False, max_length=1, verbose_name='追加经费添加状态'),
        ),
    ]
