# Generated by Django 2.0.5 on 2018-06-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0014_auto_20180607_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notififile',
            name='notifi_file_status',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notifi_id',
            field=models.IntegerField(default=1528371849, unique=True, verbose_name='通知id'),
        ),
    ]
