# Generated by Django 2.0.5 on 2018-06-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0015_auto_20180607_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addfund',
            options={'verbose_name': '追加经费', 'verbose_name_plural': '追加经费'},
        ),
        migrations.AlterModelOptions(
            name='conclusion',
            options={'verbose_name': '结题检查', 'verbose_name_plural': '结题检查'},
        ),
        migrations.AlterModelOptions(
            name='fund',
            options={'verbose_name': '经费管理', 'verbose_name_plural': '经费管理'},
        ),
        migrations.AlterModelOptions(
            name='midterm',
            options={'verbose_name': '中期检查', 'verbose_name_plural': '中期检查'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': '消息通知', 'verbose_name_plural': '消息通知'},
        ),
        migrations.AlterModelOptions(
            name='notififile',
            options={'verbose_name': '通知附件', 'verbose_name_plural': '通知附件'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目信息', 'verbose_name_plural': '项目信息'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': '成果管理', 'verbose_name_plural': '成果管理'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': '项目进度', 'verbose_name_plural': '项目进度'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='notifi_id',
            field=models.IntegerField(default=1528378652, unique=True, verbose_name='通知id'),
        ),
    ]
