# Generated by Django 2.0.5 on 2018-06-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0017_auto_20180607_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notifi_id',
            field=models.IntegerField(default=1528420882, unique=True, verbose_name='通知id'),
        ),
    ]
