# Generated by Django 2.0.5 on 2018-06-05 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0017_auto_20180605_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='midterm',
            old_name='midterm_cehck_point',
            new_name='midterm_check_point',
        ),
    ]
