# Generated by Django 2.0.5 on 2018-06-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtp_project', '0019_conclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conclusion',
            name='conclusion_check_point',
            field=models.CharField(choices=[('0', ''), ('1', '教师审核'), ('2', '管理员审核')], default='0', max_length=1, verbose_name='审核节点'),
        ),
        migrations.AlterField(
            model_name='midterm',
            name='midterm_check_point',
            field=models.CharField(choices=[('0', ''), ('1', '教师审核'), ('2', '管理员审核')], default='0', max_length=1, verbose_name='审核节点'),
        ),
    ]
